version: "3.8"

services:
  # PostgreSQL database container
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1213
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js application container
  app:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:1213@db:5432/testdb"
    command: ["npm", "run", "start"]

volumes:
  postgres_data:
